### ISSUE TITLE
[FEATURE REQUEST] Use timestamps to name backups

### ISSUE THREAD

**Issue by DrissiReda** [L1ghtmann/IAmLazy#19]
When a backup is created it gets named `IAmLazy-X.tar.gz` X being the iteration.

This isn't very helpful, because as we move files around/upload them somewhere for safekeeping the creation date metadata gets modified. It would be better if we could have something like `IAmLazy-DD-MM-YYYYTHH-MM-SS.tar.gz` .

**Comment by L1ghtmann** [comment]
Hmm, hadn't really considered that the archive's metadata would be of much use, but I do see your point. 

Though naming the backups by their time of creation would resolve that, I'm not a huge fan of the long filenames.

If you happen to have a minute, would you mind extracting one of those moved backups and checking whether the resulting directory (or the debs within it) retain their original creation date?

**Comment by DrissiReda** [comment]
I'll check when I get home. But adding timestamp to a backup name shouldn't be that long, or we can just name them exclusively as timestamps? It's quite customary for backups, since you use the full path as a name, e.g `/path/to/backups/tweaks/TS.tar.xz`

**Comment by DrissiReda** [comment]
@L1ghtmann 
The resulting directory creation time equals the time of the extraction operation. The debs within retain their original creation date though.

**Comment by L1ghtmann** [comment]
Gotcha, thanks for checking.

Given that the debs retain the original creation timestamp, and changing the archive name would break compatibility with older backups, I don't think I'll be changing anything for the time being. 

When I saw your issue, I initially thought I'd create a hidden file in the archive so that there'd be a record of the initial creation date/time, but the user would have to extract the archive to see that and if they're doing that they could just look at the debs since they retain their metadata. 

I'll leave this issue open as a reminder for the future though. Appreciate you bringing it up!

**Comment by L1ghtmann** [comment]
Quick note: the archived files' creation dates can be viewed with `tar -tvf archiveName.tar.gz` (rounded to minute) or `tar -tv --full-time -f archiveName.tar.gz` (rounded to second) without having to extract the contents.

**Comment by DrissiReda** [comment]
Didn’t think of that. Should’ve checked tar man. 

Also about compatibility you’re right. You’d have to change the automatic latest backup search to include the new and old file format but it shouldn’t be too hard. 

I just thought of adding timestamps for convenience sake. I manage backup export to my personal cloud for different apps/machines. And the timestamp gives me a very quick idea about what would be included in the backup.

 Same for tweaks, gives me an idea of which setup I had for each backup.

**Comment by L1ghtmann** [comment]
Decided that this is worth pursuing, so will be switching the naming scheme over in v2. Thanks again for your suggestion!

**Comment by L1ghtmann** [comment]
Added in b989c61 and available in v2.0.0.
