### ISSUE TITLE
Error on Installation

### ISSUE THREAD

**Issue by iFred4iPhone** [L1ghtmann/IAmLazy#33]
iPhone 13 Pro Max on ios 15, Jailbroken with Xina15, trying to install IAmLazy but get an immediate error of me.lightmann.iamlazy (Queued) What do i need to do?

**Comment by L1ghtmann** [comment]
Hey! The error occurs because IAmLazy currently lacks support for iOS 15+ (and rootless jailbreaks in general). I will very likely add support once the iOS 15 jailbreaks are in a stable state. My only device is currently sitting on iOS 14 and I don't plan on updating it until the jailbreaks' issues have been sorted and I can trust that they won't change too drastically. Going to close this for now in favor of #30. Appreciate your interest and support!
