### ISSUE TITLE
Failed to generate list of packages

### ISSUE THREAD

**Issue by udomoody** [L1ghtmann/IAmLazy#50]
I always get the error "Failed to generate list of packages"

The details are shown here
![EB1918E9-7A2C-4A18-9585-99FDE44E5B49](https://github.com/user-attachments/assets/f0bdc930-8c2c-48c0-8ce4-aee362c182f6)

**Comment by L1ghtmann** [comment]
Hey, thanks for reporting this. It seems like Canister -- the API used for package identification -- is having some issues at the moment. Will update here when I learn more

**Comment by L1ghtmann** [comment]
@udomoody should be fixed now

**Comment by udomoody** [comment]
> @udomoody should be fixed now

Unfortunately I still get the same error rigth now

**Comment by rabea98** [comment]
Same error
![image](https://github.com/user-attachments/assets/2dbb6cd2-ab6a-46e0-aa5e-0cce8e6f76f4)

**Comment by Skrrtin69** [comment]
Also experiencing this error.
![7DCF15A8-2CB8-4D7B-BCC6-DD56DC2C58DB](https://github.com/user-attachments/assets/dc4e8227-eff1-4008-8a2a-b3dae2a21f82)

**Comment by L1ghtmann** [comment]
Hi, thank you all for bringing this to my attention! It seems Canister -- the API used for package identification -- underwent breaking changes recently (5 days ago). I have updated things on my end and submitted v2.6.2 with the changes. Should be live soon. Please confirm the problem is resolved when it's available

**Comment by udomoody** [comment]
Thank you, it works great now!
